version: '3.3'
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./nextjs-ts-app/
      dockerfile: Dockerfile
    volumes:
      - ./nextjs-ts-app:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
  database:
    image: 'postgres:12'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/posgresql/data/
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
volumes:
  database:
    driver: local