import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chocolate Insights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cocoa-icon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className="max-w-4xl">
          <h1 className={styles.title} id="about-us">
            About Us
          </h1>
          <div className={styles.description}>
          <h2 className="leading-loose">
            We are an organization whose mission is to <b>support all</b> of those involved in the <b>craft chocolate process</b>.
            Not just from bean-to-bar, but from when the cacao is being grown to the moment the end product hits the {"consumer's taste buds. "} 
            <b>Our specialty</b> lies in <b>creating impactful software</b> to help with every aspect of this craft.
          </h2>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
